project:
  type: book
  output-dir: docs

output:
  html:
    toc: true
    toc-location: right
    toc-depth: 2
    theme: cosmos
    css: styles.css
  pdf:
    toc: true
    toc-location: right
    toc-depth: 2
    theme: cosmos
    css: styles.css


book:
  title: "Introduction to Polars"
  subtitle: "A Beginners Guide to Data Analysis with Polars in Python"
  author: "Nathaniel Clark"
  date: "2025-04-20"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
  appendices: 
    - appendix1.qmd
    - appendix2.qmd
  navbar:
    background: primary

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 2
  pdf:
    toc: true
    toc-depth: 2