project:
  type: website

website:
  title: "Introduction to Polars"
  description: "A Beginners Guide to Data Analysis with Polars in Python"
  repo-url: https://github.com/r-wasm/quarto-live
  repo-actions: [issue]
  page-navigation: true
  sidebar:
    contents:
      - href: index.qmd
      - section: Getting Started
        contents:
         - about.qmd
         - intro.qmd
         - installation.qmd
         - chapter1.qmd
         - chapter2.qmd
      - section: Appendices
        contents:
          - appendix1.qmd
          - appendix2.qmd
theme:
  light: cosmo
  dark: darkly

page-footer: 
  border: true
  left: "Nathaniel Clark 2025©"
  right: 
    - icon: linkedin
      href: https://www.linkedin.com/in/nathaniel-e-clark/
    - icon: github
      href: