project:
  type: book
  output-dir: ../_site/intro_to_polars

output:
  html:
    toc: true
    toc-location: right
    toc-depth: 2
    theme: cosmos
    css: styles.css
  pdf:
    toc: true
    toc-location: right
    toc-depth: 2
    theme: cosmos
    css: styles.css
output-dir: _book

book:
  title: "Introduction to Polars"
  subtitle: "A Beginners Guide to Data Analysis with Polars in Python"
  author: "Nathaniel Clark"
  date: "2025-04-20"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
  appendices: 
    - appendix1.qmd
  navbar:
    background: primary

format:
  html:
    theme: cosmos
    css: styles.css
  pdf:
    toc: true
    toc-location: right
    toc-depth: 2
    theme: cosmos
    css: styles.css